name: Java CI with Maven - Test and package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Récupère le code du dépôt

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Configure Java
        with:
          java-version: '17'
          distribution: 'temurin'  # Utilise Temurin JDK

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Exécute Maven pour compiler et empaqueter le projet
